import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

import '../constants/app_colors.dart';
import '../../models/prayer_time_model.dart';
import 'timezone_service.dart';

class CityPreset {
  final String city;
  final String country;
  final double lat;
  final double lng;
  final String ianaTimeZone;
  final CalculationMethod defaultMethod;

  const CityPreset({
    required this.city,
    required this.country,
    required this.lat,
    required this.lng,
    required this.ianaTimeZone,
    this.defaultMethod = CalculationMethod.muslimWorldLeague,
  });
}

class LocationService {
  static const List<CityPreset> popularIslamicCities = [
    CityPreset(
      city: 'Istanbul',
      country: 'Turkey',
      lat: 41.0082,
      lng: 28.9784,
      ianaTimeZone: 'Europe/Istanbul',
      defaultMethod: CalculationMethod.turkeyDiyanet,
    ),
    CityPreset(
      city: 'Ankara',
      country: 'Turkey',
      lat: 39.9334,
      lng: 32.8597,
      ianaTimeZone: 'Europe/Istanbul',
      defaultMethod: CalculationMethod.turkeyDiyanet,
    ),
    CityPreset(
      city: 'Izmir',
      country: 'Turkey',
      lat: 38.4237,
      lng: 27.1428,
      ianaTimeZone: 'Europe/Istanbul',
      defaultMethod: CalculationMethod.turkeyDiyanet,
    ),
    CityPreset(
      city: 'Bursa',
      country: 'Turkey',
      lat: 40.1885,
      lng: 29.0610,
      ianaTimeZone: 'Europe/Istanbul',
      defaultMethod: CalculationMethod.turkeyDiyanet,
    ),
    CityPreset(
      city: 'Antalya',
      country: 'Turkey',
      lat: 36.8969,
      lng: 30.7133,
      ianaTimeZone: 'Europe/Istanbul',
      defaultMethod: CalculationMethod.turkeyDiyanet,
    ),
    CityPreset(
      city: 'Konya',
      country: 'Turkey',
      lat: 37.8746,
      lng: 32.4932,
      ianaTimeZone: 'Europe/Istanbul',
      defaultMethod: CalculationMethod.turkeyDiyanet,
    ),
    CityPreset(
      city: 'Makkah',
      country: 'Saudi Arabia',
      lat: 21.4225,
      lng: 39.8262,
      ianaTimeZone: 'Asia/Riyadh',
      defaultMethod: CalculationMethod.ummAlQuraMakkah,
    ),
    CityPreset(
      city: 'Madinah',
      country: 'Saudi Arabia',
      lat: 24.4672,
      lng: 39.6111,
      ianaTimeZone: 'Asia/Riyadh',
      defaultMethod: CalculationMethod.ummAlQuraMakkah,
    ),
    CityPreset(
      city: 'Riyadh',
      country: 'Saudi Arabia',
      lat: 24.7136,
      lng: 46.6753,
      ianaTimeZone: 'Asia/Riyadh',
      defaultMethod: CalculationMethod.ummAlQuraMakkah,
    ),
    CityPreset(
      city: 'Jeddah',
      country: 'Saudi Arabia',
      lat: 21.5433,
      lng: 39.1728,
      ianaTimeZone: 'Asia/Riyadh',
      defaultMethod: CalculationMethod.ummAlQuraMakkah,
    ),
    CityPreset(
      city: 'Jerusalem (Al-Quds)',
      country: 'Palestine',
      lat: 31.7767,
      lng: 35.2345,
      ianaTimeZone: 'Asia/Jerusalem',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Cairo',
      country: 'Egypt',
      lat: 30.0444,
      lng: 31.2357,
      ianaTimeZone: 'Africa/Cairo',
      defaultMethod: CalculationMethod.egyptianGeneralAuthority,
    ),
    CityPreset(
      city: 'Alexandria',
      country: 'Egypt',
      lat: 31.2001,
      lng: 29.9187,
      ianaTimeZone: 'Africa/Cairo',
      defaultMethod: CalculationMethod.egyptianGeneralAuthority,
    ),
    CityPreset(
      city: 'Dubai',
      country: 'United Arab Emirates',
      lat: 25.2048,
      lng: 55.2708,
      ianaTimeZone: 'Asia/Dubai',
      defaultMethod: CalculationMethod.dubai,
    ),
    CityPreset(
      city: 'Abu Dhabi',
      country: 'United Arab Emirates',
      lat: 24.4539,
      lng: 54.3773,
      ianaTimeZone: 'Asia/Dubai',
      defaultMethod: CalculationMethod.dubai,
    ),
    CityPreset(
      city: 'Doha',
      country: 'Qatar',
      lat: 25.2854,
      lng: 51.5310,
      ianaTimeZone: 'Asia/Qatar',
      defaultMethod: CalculationMethod.qatar,
    ),
    CityPreset(
      city: 'Kuwait City',
      country: 'Kuwait',
      lat: 29.3759,
      lng: 47.9774,
      ianaTimeZone: 'Asia/Kuwait',
      defaultMethod: CalculationMethod.kuwait,
    ),
    CityPreset(
      city: 'Muscat',
      country: 'Oman',
      lat: 23.5880,
      lng: 58.3829,
      ianaTimeZone: 'Asia/Muscat',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Manama',
      country: 'Bahrain',
      lat: 26.2285,
      lng: 50.5860,
      ianaTimeZone: 'Asia/Bahrain',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Karachi',
      country: 'Pakistan',
      lat: 24.8607,
      lng: 67.0011,
      ianaTimeZone: 'Asia/Karachi',
      defaultMethod: CalculationMethod.universityOfIslamicSciencesKarachi,
    ),
    CityPreset(
      city: 'Lahore',
      country: 'Pakistan',
      lat: 31.5204,
      lng: 74.3587,
      ianaTimeZone: 'Asia/Karachi',
      defaultMethod: CalculationMethod.universityOfIslamicSciencesKarachi,
    ),
    CityPreset(
      city: 'Islamabad',
      country: 'Pakistan',
      lat: 33.6844,
      lng: 73.0479,
      ianaTimeZone: 'Asia/Karachi',
      defaultMethod: CalculationMethod.universityOfIslamicSciencesKarachi,
    ),
    CityPreset(
      city: 'Dhaka',
      country: 'Bangladesh',
      lat: 23.8103,
      lng: 90.4125,
      ianaTimeZone: 'Asia/Dhaka',
      defaultMethod: CalculationMethod.universityOfIslamicSciencesKarachi,
    ),
    CityPreset(
      city: 'Jakarta',
      country: 'Indonesia',
      lat: -6.2088,
      lng: 106.8456,
      ianaTimeZone: 'Asia/Jakarta',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Kuala Lumpur',
      country: 'Malaysia',
      lat: 3.1390,
      lng: 101.6869,
      ianaTimeZone: 'Asia/Kuala_Lumpur',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Singapore',
      country: 'Singapore',
      lat: 1.3521,
      lng: 103.8198,
      ianaTimeZone: 'Asia/Singapore',
      defaultMethod: CalculationMethod.singapore,
    ),
    CityPreset(
      city: 'London',
      country: 'United Kingdom',
      lat: 51.5074,
      lng: -0.1278,
      ianaTimeZone: 'Europe/London',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Birmingham',
      country: 'United Kingdom',
      lat: 52.4862,
      lng: -1.8904,
      ianaTimeZone: 'Europe/London',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Manchester',
      country: 'United Kingdom',
      lat: 53.4808,
      lng: -2.2426,
      ianaTimeZone: 'Europe/London',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Paris',
      country: 'France',
      lat: 48.8566,
      lng: 2.3522,
      ianaTimeZone: 'Europe/Paris',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Berlin',
      country: 'Germany',
      lat: 52.5200,
      lng: 13.4050,
      ianaTimeZone: 'Europe/Berlin',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'New York',
      country: 'United States',
      lat: 40.7128,
      lng: -74.0060,
      ianaTimeZone: 'America/New_York',
      defaultMethod: CalculationMethod.islamicSocietyOfNorthAmerica,
    ),
    CityPreset(
      city: 'Chicago',
      country: 'United States',
      lat: 41.8781,
      lng: -87.6298,
      ianaTimeZone: 'America/Chicago',
      defaultMethod: CalculationMethod.islamicSocietyOfNorthAmerica,
    ),
    CityPreset(
      city: 'Los Angeles',
      country: 'United States',
      lat: 34.0522,
      lng: -118.2437,
      ianaTimeZone: 'America/Los_Angeles',
      defaultMethod: CalculationMethod.islamicSocietyOfNorthAmerica,
    ),
    CityPreset(
      city: 'Houston',
      country: 'United States',
      lat: 29.7604,
      lng: -95.3698,
      ianaTimeZone: 'America/Chicago',
      defaultMethod: CalculationMethod.islamicSocietyOfNorthAmerica,
    ),
    CityPreset(
      city: 'Toronto',
      country: 'Canada',
      lat: 43.6532,
      lng: -79.3832,
      ianaTimeZone: 'America/Toronto',
      defaultMethod: CalculationMethod.islamicSocietyOfNorthAmerica,
    ),
    CityPreset(
      city: 'Sydney',
      country: 'Australia',
      lat: -33.8688,
      lng: 151.2093,
      ianaTimeZone: 'Australia/Sydney',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Melbourne',
      country: 'Australia',
      lat: -37.8136,
      lng: 144.9631,
      ianaTimeZone: 'Australia/Melbourne',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Tokyo',
      country: 'Japan',
      lat: 35.6762,
      lng: 139.6503,
      ianaTimeZone: 'Asia/Tokyo',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Casablanca',
      country: 'Morocco',
      lat: 33.5731,
      lng: -7.5898,
      ianaTimeZone: 'Africa/Casablanca',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Algiers',
      country: 'Algeria',
      lat: 36.7538,
      lng: 3.0588,
      ianaTimeZone: 'Africa/Algiers',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Tunis',
      country: 'Tunisia',
      lat: 36.8065,
      lng: 10.1815,
      ianaTimeZone: 'Africa/Tunis',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Amman',
      country: 'Jordan',
      lat: 31.9454,
      lng: 35.9284,
      ianaTimeZone: 'Asia/Amman',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Auckland',
      country: 'New Zealand',
      lat: -36.8485,
      lng: 174.7633,
      ianaTimeZone: 'Pacific/Auckland',
      defaultMethod: CalculationMethod.muslimWorldLeague,
    ),
    CityPreset(
      city: 'Honolulu',
      country: 'United States',
      lat: 21.3069,
      lng: -157.8583,
      ianaTimeZone: 'Pacific/Honolulu',
      defaultMethod: CalculationMethod.islamicSocietyOfNorthAmerica,
    ),
  ];

  /// Shows the required permission explanation dialog before invoking OS location prompt.
  static Future<bool> showPermissionRationaleDialog(
    BuildContext context,
  ) async {
    final result = await showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: AppColors.primaryEmerald.withOpacity(0.12),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.location_on,
                color: AppColors.primaryEmerald,
                size: 24,
              ),
            ),
            const SizedBox(width: 12),
            const Expanded(
              child: Text(
                'Location Access',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
              ),
            ),
          ],
        ),
        content: const Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Enable Location for Accurate Prayer Times',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 15,
                color: AppColors.primaryEmerald,
              ),
            ),
            SizedBox(height: 10),
            Text(
              'We only access your device location to provide accurate prayer times and location-based features. Your personal data remains private. You can safely enable location services.',
              style: TextStyle(
                fontSize: 13,
                height: 1.45,
                color: AppColors.textSecondaryLight,
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: const Text('Not Now', style: TextStyle(color: Colors.grey)),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(ctx, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.primaryEmerald,
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
            child: const Text('Continue'),
          ),
        ],
      ),
    );
    return result ?? false;
  }

  /// Checks and requests device GPS location.
  static Future<Position?> requestDeviceLocation(BuildContext context) async {
    bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text(
              'Location services are disabled on your device. Please turn on GPS.',
            ),
            backgroundColor: AppColors.warning,
          ),
        );
      }
      return null;
    }

    LocationPermission permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      if (context.mounted) {
        final proceed = await showPermissionRationaleDialog(context);
        if (!proceed) return null;
      }
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'Location permission denied. Using manual location.',
              ),
              backgroundColor: AppColors.warning,
            ),
          );
        }
        return null;
      }
    }

    if (permission == LocationPermission.deniedForever) {
      if (context.mounted) {
        showDialog(
          context: context,
          builder: (ctx) => AlertDialog(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
            title: const Text('Permission Permanently Denied'),
            content: const Text(
              'Location permission is permanently denied. You can enable it from system App Settings or select a city manually.',
              style: TextStyle(fontSize: 13, height: 1.4),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: const Text('Cancel'),
              ),
              ElevatedButton(
                onPressed: () {
                  Navigator.pop(ctx);
                  Geolocator.openAppSettings();
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primaryEmerald,
                ),
                child: const Text(
                  'Open Settings',
                  style: TextStyle(color: Colors.white),
                ),
              ),
            ],
          ),
        );
      }
      return null;
    }

    try {
      final position = await Geolocator.getCurrentPosition(
        locationSettings: const LocationSettings(
          accuracy: LocationAccuracy.high,
          timeLimit: Duration(seconds: 10),
        ),
      );
      return position;
    } catch (_) {
      try {
        return await Geolocator.getLastKnownPosition();
      } catch (_) {
        return null;
      }
    }
  }

  /// Approximate nearest city from coordinates among preset list.
  static CityPreset findNearestCity(double lat, double lng) {
    CityPreset nearest = popularIslamicCities.first;
    double minDistance = double.infinity;

    for (final c in popularIslamicCities) {
      final d = Geolocator.distanceBetween(lat, lng, c.lat, c.lng);
      if (d < minDistance) {
        minDistance = d;
        nearest = c;
      }
    }
    return nearest;
  }

  /// Resolves the IANA timezone and intelligent calculation method for given coordinates.
  static ({String ianaTimeZone, CalculationMethod defaultMethod})
      resolveLocationMetadata(
    double lat,
    double lng, {
    String city = '',
    String country = '',
  }) {
    final nearest = findNearestCity(lat, lng);
    final detectedTz = TimezoneService.detectIanaTimeZone(
      lat: lat,
      lng: lng,
      country: country.isNotEmpty ? country : nearest.country,
      city: city.isNotEmpty ? city : nearest.city,
    );

    return (
      ianaTimeZone: detectedTz,
      defaultMethod: nearest.defaultMethod,
    );
  }

  static const Map<String, Map<String, String>> _localizedCities = {
    'istanbul': {
      'ar': 'إسطنبول',
      'de': 'Istanbul',
      'en': 'Istanbul',
      'es': 'Estambul',
      'fr': 'Istanbul',
      'id': 'Istanbul',
      'ms': 'Istanbul',
      'pt': 'Istambul',
      'ru': 'Стамбул',
      'tr': 'İstanbul',
      'ur': 'استنبول',
    },
    'ankara': {
      'ar': 'أنقرة',
      'de': 'Ankara',
      'en': 'Ankara',
      'es': 'Ankara',
      'fr': 'Ankara',
      'id': 'Ankara',
      'ms': 'Ankara',
      'pt': 'Ancara',
      'ru': 'Анкара',
      'tr': 'Ankara',
      'ur': 'انقرہ',
    },
    'izmir': {
      'ar': 'إزمير',
      'de': 'Izmir',
      'en': 'Izmir',
      'es': 'Esmirna',
      'fr': 'Izmir',
      'id': 'Izmir',
      'ms': 'Izmir',
      'pt': 'Esmirna',
      'ru': 'Измир',
      'tr': 'İzmir',
      'ur': 'ازمیر',
    },
    'bursa': {
      'ar': 'بورصة',
      'de': 'Bursa',
      'en': 'Bursa',
      'es': 'Bursa',
      'fr': 'Brousse',
      'id': 'Bursa',
      'ms': 'Bursa',
      'pt': 'Bursa',
      'ru': 'Бурса',
      'tr': 'Bursa',
      'ur': 'بروصہ',
    },
    'antalya': {
      'ar': 'أنطاليا',
      'de': 'Antalya',
      'en': 'Antalya',
      'es': 'Antalya',
      'fr': 'Antalya',
      'id': 'Antalya',
      'ms': 'Antalya',
      'pt': 'Antália',
      'ru': 'Анталья',
      'tr': 'Antalya',
      'ur': 'انطالیہ',
    },
    'konya': {
      'ar': 'قونية',
      'de': 'Konya',
      'en': 'Konya',
      'es': 'Konya',
      'fr': 'Konya',
      'id': 'Konya',
      'ms': 'Konya',
      'pt': 'Cônia',
      'ru': 'Конья',
      'tr': 'Konya',
      'ur': 'قونیہ',
    },
    'makkah': {
      'ar': 'مكة المكرمة',
      'de': 'Mekka',
      'en': 'Makkah',
      'es': 'La Meca',
      'fr': 'La Mecque',
      'id': 'Makkah',
      'ms': 'Makkah',
      'pt': 'Meca',
      'ru': 'Мекка',
      'tr': 'Mekke',
      'ur': 'مکہ مکرمہ',
    },
    'mecca': {
      'ar': 'مكة المكرمة',
      'de': 'Mekka',
      'en': 'Makkah',
      'es': 'La Meca',
      'fr': 'La Mecque',
      'id': 'Makkah',
      'ms': 'Makkah',
      'pt': 'Meca',
      'ru': 'Мекка',
      'tr': 'Mekke',
      'ur': 'مکہ مکرمہ',
    },
    'madinah': {
      'ar': 'المدينة المنورة',
      'de': 'Medina',
      'en': 'Madinah',
      'es': 'Medina',
      'fr': 'Médine',
      'id': 'Madinah',
      'ms': 'Madinah',
      'pt': 'Medina',
      'ru': 'Медина',
      'tr': 'Medine',
      'ur': 'مدینہ منورہ',
    },
    'medina': {
      'ar': 'المدينة المنورة',
      'de': 'Medina',
      'en': 'Madinah',
      'es': 'Medina',
      'fr': 'Médine',
      'id': 'Madinah',
      'ms': 'Madinah',
      'pt': 'Medina',
      'ru': 'Медина',
      'tr': 'Medine',
      'ur': 'مدینہ منورہ',
    },
    'riyadh': {
      'ar': 'الرياض',
      'de': 'Riad',
      'en': 'Riyadh',
      'es': 'Riad',
      'fr': 'Riyad',
      'id': 'Riyadh',
      'ms': 'Riyadh',
      'pt': 'Riade',
      'ru': 'Эр-Рияд',
      'tr': 'Riyad',
      'ur': 'ریاض',
    },
    'jeddah': {
      'ar': 'جدة',
      'de': 'Dschidda',
      'en': 'Jeddah',
      'es': 'Yeda',
      'fr': 'Djeddah',
      'id': 'Jeddah',
      'ms': 'Jeddah',
      'pt': 'Gidá',
      'ru': 'Джидда',
      'tr': 'Cidde',
      'ur': 'جدہ',
    },
    'cairo': {
      'ar': 'القاهرة',
      'de': 'Kairo',
      'en': 'Cairo',
      'es': 'El Cairo',
      'fr': 'Le Caire',
      'id': 'Kairo',
      'ms': 'Kaherah',
      'pt': 'Cairo',
      'ru': 'Каир',
      'tr': 'Kahire',
      'ur': 'قاہرہ',
    },
    'alexandria': {
      'ar': 'الإسكندرية',
      'de': 'Alexandria',
      'en': 'Alexandria',
      'es': 'Alejandría',
      'fr': 'Alexandrie',
      'id': 'Iskandariyah',
      'ms': 'Iskandariah',
      'pt': 'Alexandria',
      'ru': 'Александрия',
      'tr': 'İskenderiye',
      'ur': 'اسکندریہ',
    },
    'dubai': {
      'ar': 'دبي',
      'de': 'Dubai',
      'en': 'Dubai',
      'es': 'Dubái',
      'fr': 'Dubaï',
      'id': 'Dubai',
      'ms': 'Dubai',
      'pt': 'Dubai',
      'ru': 'Дубай',
      'tr': 'Dubai',
      'ur': 'دبئی',
    },
    'abu dhabi': {
      'ar': 'أبو ظبي',
      'de': 'Abu Dhabi',
      'en': 'Abu Dhabi',
      'es': 'Abu Dabi',
      'fr': 'Abou Dabi',
      'id': 'Abu Dhabi',
      'ms': 'Abu Dhabi',
      'pt': 'Abu Dhabi',
      'ru': 'Абу-Даби',
      'tr': 'Abu Dabi',
      'ur': 'ابوظہبی',
    },
    'doha': {
      'ar': 'الدوحة',
      'de': 'Doha',
      'en': 'Doha',
      'es': 'Doha',
      'fr': 'Doha',
      'id': 'Doha',
      'ms': 'Doha',
      'pt': 'Doha',
      'ru': 'Доха',
      'tr': 'Doha',
      'ur': 'دوحہ',
    },
    'kuwait city': {
      'ar': 'مدينة الكويت',
      'de': 'Kuwait-Stadt',
      'en': 'Kuwait City',
      'es': 'Ciudad de Kuwait',
      'fr': 'Koweït',
      'id': 'Kota Kuwait',
      'ms': 'Bandar Kuwait',
      'pt': 'Cidade do Kuwait',
      'ru': 'Эль-Кувейт',
      'tr': 'Kuveyt',
      'ur': 'کویت شہر',
    },
    'kuwait': {
      'ar': 'الكويت',
      'de': 'Kuwait',
      'en': 'Kuwait',
      'es': 'Kuwait',
      'fr': 'Koweït',
      'id': 'Kuwait',
      'ms': 'Kuwait',
      'pt': 'Kuwait',
      'ru': 'Кувейт',
      'tr': 'Kuveyt',
      'ur': 'کویت',
    },
    'manama': {
      'ar': 'المنامة',
      'de': 'Manama',
      'en': 'Manama',
      'es': 'Manama',
      'fr': 'Manama',
      'id': 'Manama',
      'ms': 'Manama',
      'pt': 'Manama',
      'ru': 'Манама',
      'tr': 'Manama',
      'ur': 'منامہ',
    },
    'muscat': {
      'ar': 'مسقط',
      'de': 'Maskat',
      'en': 'Muscat',
      'es': 'Mascate',
      'fr': 'Mascate',
      'id': 'Muskat',
      'ms': 'Muscat',
      'pt': 'Mascate',
      'ru': 'Маскат',
      'tr': 'Maskat',
      'ur': 'مسقط',
    },
    'amman': {
      'ar': 'عمّان',
      'de': 'Amman',
      'en': 'Amman',
      'es': 'Amán',
      'fr': 'Amman',
      'id': 'Amman',
      'ms': 'Amman',
      'pt': 'Amã',
      'ru': 'Амман',
      'tr': 'Amman',
      'ur': 'عمان',
    },
    'beirut': {
      'ar': 'بيروت',
      'de': 'Beirut',
      'en': 'Beirut',
      'es': 'Beirut',
      'fr': 'Beyrouth',
      'id': 'Beirut',
      'ms': 'Beirut',
      'pt': 'Beirute',
      'ru': 'Бейрут',
      'tr': 'Beyrut',
      'ur': 'بیروت',
    },
    'jerusalem': {
      'ar': 'القدس الشريف',
      'de': 'Jerusalem',
      'en': 'Jerusalem',
      'es': 'Jerusalén',
      'fr': 'Jérusalem',
      'id': 'Yerusalem',
      'ms': 'Baitulmaqdis',
      'pt': 'Jerusalém',
      'ru': 'Иерусалим',
      'tr': 'Kudüs',
      'ur': 'القدس',
    },
    'baghdad': {
      'ar': 'بغداد',
      'de': 'Bagdad',
      'en': 'Baghdad',
      'es': 'Bagdad',
      'fr': 'Bagdad',
      'id': 'Bagdad',
      'ms': 'Baghdad',
      'pt': 'Bagdá',
      'ru': 'Багдад',
      'tr': 'Bağdat',
      'ur': 'بغداد',
    },
    'tehran': {
      'ar': 'طهران',
      'de': 'Teheran',
      'en': 'Tehran',
      'es': 'Teherán',
      'fr': 'Téhéran',
      'id': 'Teheran',
      'ms': 'Tehran',
      'pt': 'Teerã',
      'ru': 'Тегеран',
      'tr': 'Tahran',
      'ur': 'تہران',
    },
    'karachi': {
      'ar': 'كراتشي',
      'de': 'Karatschi',
      'en': 'Karachi',
      'es': 'Karachi',
      'fr': 'Karachi',
      'id': 'Karachi',
      'ms': 'Karachi',
      'pt': 'Carachi',
      'ru': 'Карачи',
      'tr': 'Karaçi',
      'ur': 'کراچی',
    },
    'lahore': {
      'ar': 'لاهور',
      'de': 'Lahore',
      'en': 'Lahore',
      'es': 'Lahore',
      'fr': 'Lahore',
      'id': 'Lahore',
      'ms': 'Lahore',
      'pt': 'Lahore',
      'ru': 'Лахор',
      'tr': 'Lahor',
      'ur': 'لاہور',
    },
    'islamabad': {
      'ar': 'إسلام آباد',
      'de': 'Islamabad',
      'en': 'Islamabad',
      'es': 'Islamabad',
      'fr': 'Islamabad',
      'id': 'Islamabad',
      'ms': 'Islamabad',
      'pt': 'Islamabad',
      'ru': 'Исламабад',
      'tr': 'İslamabad',
      'ur': 'اسلام آباد',
    },
    'dhaka': {
      'ar': 'دكا',
      'de': 'Dhaka',
      'en': 'Dhaka',
      'es': 'Daca',
      'fr': 'Dacca',
      'id': 'Dhaka',
      'ms': 'Dhaka',
      'pt': 'Daca',
      'ru': 'Дакка',
      'tr': 'Dakka',
      'ur': 'ڈھاکہ',
    },
    'jakarta': {
      'ar': 'جاكرتا',
      'de': 'Jakarta',
      'en': 'Jakarta',
      'es': 'Yakarta',
      'fr': 'Jakarta',
      'id': 'Jakarta',
      'ms': 'Jakarta',
      'pt': 'Jacarta',
      'ru': 'Джакарта',
      'tr': 'Cakarta',
      'ur': 'جکارتہ',
    },
    'kuala lumpur': {
      'ar': 'كوالالمبور',
      'de': 'Kuala Lumpur',
      'en': 'Kuala Lumpur',
      'es': 'Kuala Lumpur',
      'fr': 'Kuala Lumpur',
      'id': 'Kuala Lumpur',
      'ms': 'Kuala Lumpur',
      'pt': 'Kuala Lumpur',
      'ru': 'Куала-Лумпур',
      'tr': 'Kuala Lumpur',
      'ur': 'کوالالمپور',
    },
    'singapore': {
      'ar': 'سنغافورة',
      'de': 'Singapur',
      'en': 'Singapore',
      'es': 'Singapur',
      'fr': 'Singapour',
      'id': 'Singapura',
      'ms': 'Singapura',
      'pt': 'Singapura',
      'ru': 'Сингапур',
      'tr': 'Singapur',
      'ur': 'سنگاپور',
    },
    'london': {
      'ar': 'لندن',
      'de': 'London',
      'en': 'London',
      'es': 'Londres',
      'fr': 'Londres',
      'id': 'London',
      'ms': 'London',
      'pt': 'Londres',
      'ru': 'Лондон',
      'tr': 'Londra',
      'ur': 'لندن',
    },
    'paris': {
      'ar': 'باريس',
      'de': 'Paris',
      'en': 'Paris',
      'es': 'París',
      'fr': 'Paris',
      'id': 'Paris',
      'ms': 'Paris',
      'pt': 'Paris',
      'ru': 'Париж',
      'tr': 'Paris',
      'ur': 'پیرس',
    },
    'berlin': {
      'ar': 'برلين',
      'de': 'Berlin',
      'en': 'Berlin',
      'es': 'Berlín',
      'fr': 'Berlin',
      'id': 'Berlin',
      'ms': 'Berlin',
      'pt': 'Berlim',
      'ru': 'Берлин',
      'tr': 'Berlin',
      'ur': 'برلن',
    },
    'new york': {
      'ar': 'نيويورك',
      'de': 'New York',
      'en': 'New York',
      'es': 'Nueva York',
      'fr': 'New York',
      'id': 'New York',
      'ms': 'New York',
      'pt': 'Nova York',
      'ru': 'Нью-Йорк',
      'tr': 'New York',
      'ur': 'نیویارک',
    },
    'toronto': {
      'ar': 'تورونتو',
      'de': 'Toronto',
      'en': 'Toronto',
      'es': 'Toronto',
      'fr': 'Toronto',
      'id': 'Toronto',
      'ms': 'Toronto',
      'pt': 'Toronto',
      'ru': 'Торонто',
      'tr': 'Toronto',
      'ur': 'ٹورنٹو',
    },
    'sydney': {
      'ar': 'سيدني',
      'de': 'Sydney',
      'en': 'Sydney',
      'es': 'Sídney',
      'fr': 'Sydney',
      'id': 'Sydney',
      'ms': 'Sydney',
      'pt': 'Sydney',
      'ru': 'Сидней',
      'tr': 'Sidney',
      'ur': 'سڈنی',
    },
    'tokyo': {
      'ar': 'طوكيو',
      'de': 'Tokio',
      'en': 'Tokyo',
      'es': 'Tokio',
      'fr': 'Tokyo',
      'id': 'Tokyo',
      'ms': 'Tokyo',
      'pt': 'Tóquio',
      'ru': 'Токио',
      'tr': 'Tokyo',
      'ur': 'ٹوکیو',
    },
    'casablanca': {
      'ar': 'الدار البيضاء',
      'de': 'Casablanca',
      'en': 'Casablanca',
      'es': 'Casablanca',
      'fr': 'Casablanca',
      'id': 'Casablanca',
      'ms': 'Casablanca',
      'pt': 'Casablanca',
      'ru': 'Касабланка',
      'tr': 'Kazablanka',
      'ur': 'دار البیضاء',
    },
    'algiers': {
      'ar': 'الجزائر',
      'de': 'Algier',
      'en': 'Algiers',
      'es': 'Argel',
      'fr': 'Alger',
      'id': 'Aljir',
      'ms': 'Algiers',
      'pt': 'Argel',
      'ru': 'Алжир',
      'tr': 'Cezayir',
      'ur': 'الجزائر',
    },
    'tunis': {
      'ar': 'تونس',
      'de': 'Tunis',
      'en': 'Tunis',
      'es': 'Túnez',
      'fr': 'Tunis',
      'id': 'Tunis',
      'ms': 'Tunis',
      'pt': 'Túnis',
      'ru': 'Тунис',
      'tr': 'Tunus',
      'ur': 'تونس',
    },
  };

  static const Map<String, Map<String, String>> _localizedCountries = {
    'turkey': {
      'ar': 'تركيا',
      'de': 'Türkei',
      'en': 'Turkey',
      'es': 'Turquía',
      'fr': 'Turquie',
      'id': 'Turki',
      'ms': 'Turki',
      'pt': 'Turquia',
      'ru': 'Турция',
      'tr': 'Türkiye',
      'ur': 'ترکی',
    },
    'türkiye': {
      'ar': 'تركيا',
      'de': 'Türkei',
      'en': 'Turkey',
      'es': 'Turquía',
      'fr': 'Turquie',
      'id': 'Turki',
      'ms': 'Turki',
      'pt': 'Turquia',
      'ru': 'Турция',
      'tr': 'Türkiye',
      'ur': 'ترکی',
    },
    'saudi arabia': {
      'ar': 'المملكة العربية السعودية',
      'de': 'Saudi-Arabien',
      'en': 'Saudi Arabia',
      'es': 'Arabia Saudita',
      'fr': 'Arabie saoudite',
      'id': 'Arab Saudi',
      'ms': 'Arab Saudi',
      'pt': 'Arábia Saudita',
      'ru': 'Саудовская Аравия',
      'tr': 'Suudi Arabistan',
      'ur': 'سعودی عرب',
    },
    'egypt': {
      'ar': 'مصر',
      'de': 'Ägypten',
      'en': 'Egypt',
      'es': 'Egipto',
      'fr': 'Égypte',
      'id': 'Mesir',
      'ms': 'Mesir',
      'pt': 'Egito',
      'ru': 'Египет',
      'tr': 'Mısır',
      'ur': 'مصر',
    },
    'united arab emirates': {
      'ar': 'الإمارات العربية المتحدة',
      'de': 'Vereinigte Arabische Emirate',
      'en': 'United Arab Emirates',
      'es': 'Emiratos Árabes Unidos',
      'fr': 'Émirats arabes unis',
      'id': 'Uni Emirat Arab',
      'ms': 'Emiriah Arab Bersatu',
      'pt': 'Emirados Árabes Unidos',
      'ru': 'ОАЭ',
      'tr': 'Birleşik Arap Emirlikleri',
      'ur': 'متحدہ عرب امارات',
    },
    'uae': {
      'ar': 'الإمارات العربية المتحدة',
      'de': 'VAE',
      'en': 'UAE',
      'es': 'EAU',
      'fr': 'ÉAU',
      'id': 'UEA',
      'ms': 'EAB',
      'pt': 'EAU',
      'ru': 'ОАЭ',
      'tr': 'BAE',
      'ur': 'متحدہ عرب امارات',
    },
    'qatar': {
      'ar': 'قطر',
      'de': 'Katar',
      'en': 'Qatar',
      'es': 'Catar',
      'fr': 'Qatar',
      'id': 'Qatar',
      'ms': 'Qatar',
      'pt': 'Catar',
      'ru': 'Катар',
      'tr': 'Katar',
      'ur': 'قطر',
    },
    'kuwait': {
      'ar': 'الكويت',
      'de': 'Kuwait',
      'en': 'Kuwait',
      'es': 'Kuwait',
      'fr': 'Koweït',
      'id': 'Kuwait',
      'ms': 'Kuwait',
      'pt': 'Kuwait',
      'ru': 'Кувейт',
      'tr': 'Kuveyt',
      'ur': 'کویت',
    },
    'bahrain': {
      'ar': 'البحرين',
      'de': 'Bahrain',
      'en': 'Bahrain',
      'es': 'Baréin',
      'fr': 'Bahreïn',
      'id': 'Bahrain',
      'ms': 'Bahrain',
      'pt': 'Bahrein',
      'ru': 'Бахрейн',
      'tr': 'Bahreyn',
      'ur': 'بحرین',
    },
    'oman': {
      'ar': 'عُمان',
      'de': 'Oman',
      'en': 'Oman',
      'es': 'Omán',
      'fr': 'Oman',
      'id': 'Oman',
      'ms': 'Oman',
      'pt': 'Omã',
      'ru': 'Оман',
      'tr': 'Umman',
      'ur': 'عمان',
    },
    'jordan': {
      'ar': 'الأردن',
      'de': 'Jordanien',
      'en': 'Jordan',
      'es': 'Jordania',
      'fr': 'Jordanie',
      'id': 'Yordania',
      'ms': 'Jordan',
      'pt': 'Jordânia',
      'ru': 'Иордания',
      'tr': 'Ürdün',
      'ur': 'اردن',
    },
    'lebanon': {
      'ar': 'لبنان',
      'de': 'Libanon',
      'en': 'Lebanon',
      'es': 'Líbano',
      'fr': 'Liban',
      'id': 'Lebanon',
      'ms': 'Lubnan',
      'pt': 'Líbano',
      'ru': 'Ливан',
      'tr': 'Lübnan',
      'ur': 'لبنان',
    },
    'palestine': {
      'ar': 'فلسطين',
      'de': 'Palästina',
      'en': 'Palestine',
      'es': 'Palestina',
      'fr': 'Palestine',
      'id': 'Palestina',
      'ms': 'Palestin',
      'pt': 'Palestina',
      'ru': 'Палестина',
      'tr': 'Filistin',
      'ur': 'فلسطین',
    },
    'iraq': {
      'ar': 'العراق',
      'de': 'Irak',
      'en': 'Iraq',
      'es': 'Irak',
      'fr': 'Irak',
      'id': 'Irak',
      'ms': 'Iraq',
      'pt': 'Iraque',
      'ru': 'Ирак',
      'tr': 'Irak',
      'ur': 'عراق',
    },
    'iran': {
      'ar': 'إيران',
      'de': 'Iran',
      'en': 'Iran',
      'es': 'Irán',
      'fr': 'Iran',
      'id': 'Iran',
      'ms': 'Iran',
      'pt': 'Irã',
      'ru': 'Иран',
      'tr': 'İran',
      'ur': 'ایران',
    },
    'pakistan': {
      'ar': 'باكستان',
      'de': 'Pakistan',
      'en': 'Pakistan',
      'es': 'Pakistán',
      'fr': 'Pakistan',
      'id': 'Pakistan',
      'ms': 'Pakistan',
      'pt': 'Paquistão',
      'ru': 'Пакистан',
      'tr': 'Pakistan',
      'ur': 'پاکستان',
    },
    'bangladesh': {
      'ar': 'بنغلاديش',
      'de': 'Bangladesch',
      'en': 'Bangladesh',
      'es': 'Bangladés',
      'fr': 'Bangladesh',
      'id': 'Bangladesh',
      'ms': 'Bangladesh',
      'pt': 'Bangladesh',
      'ru': 'Бангладеш',
      'tr': 'Bangladeş',
      'ur': 'بنگلہ دیش',
    },
    'indonesia': {
      'ar': 'إندونيسيا',
      'de': 'Indonesien',
      'en': 'Indonesia',
      'es': 'Indonesia',
      'fr': 'Indonésie',
      'id': 'Indonesia',
      'ms': 'Indonesia',
      'pt': 'Indonésia',
      'ru': 'Индонезия',
      'tr': 'Endonezya',
      'ur': 'انڈونیشیا',
    },
    'malaysia': {
      'ar': 'ماليزيا',
      'de': 'Malaysia',
      'en': 'Malaysia',
      'es': 'Malasia',
      'fr': 'Malaisie',
      'id': 'Malaysia',
      'ms': 'Malaysia',
      'pt': 'Malásia',
      'ru': 'Малайзия',
      'tr': 'Malezya',
      'ur': 'ملائشیا',
    },
    'singapore': {
      'ar': 'سنغافورة',
      'de': 'Singapur',
      'en': 'Singapore',
      'es': 'Singapur',
      'fr': 'Singapour',
      'id': 'Singapura',
      'ms': 'Singapura',
      'pt': 'Singapura',
      'ru': 'Сингапур',
      'tr': 'Singapur',
      'ur': 'سنگاپور',
    },
    'united kingdom': {
      'ar': 'المملكة المتحدة',
      'de': 'Vereinigtes Königreich',
      'en': 'United Kingdom',
      'es': 'Reino Unido',
      'fr': 'Royaume-Uni',
      'id': 'Inggris Raya',
      'ms': 'United Kingdom',
      'pt': 'Reino Unido',
      'ru': 'Великобритания',
      'tr': 'Birleşik Krallık',
      'ur': 'برطانیہ',
    },
    'uk': {
      'ar': 'المملكة المتحدة',
      'de': 'UK',
      'en': 'UK',
      'es': 'Reino Unido',
      'fr': 'Royaume-Uni',
      'id': 'Inggris',
      'ms': 'UK',
      'pt': 'Reino Unido',
      'ru': 'Великобритания',
      'tr': 'Birleşik Krallık',
      'ur': 'برطانیہ',
    },
    'france': {
      'ar': 'فرنسا',
      'de': 'Frankreich',
      'en': 'France',
      'es': 'Francia',
      'fr': 'France',
      'id': 'Prancis',
      'ms': 'Perancis',
      'pt': 'França',
      'ru': 'Франция',
      'tr': 'Fransa',
      'ur': 'فرانس',
    },
    'germany': {
      'ar': 'ألمانيا',
      'de': 'Deutschland',
      'en': 'Germany',
      'es': 'Alemania',
      'fr': 'Allemagne',
      'id': 'Jerman',
      'ms': 'Jerman',
      'pt': 'Alemanha',
      'ru': 'Германия',
      'tr': 'Almanya',
      'ur': 'جرمنی',
    },
    'united states': {
      'ar': 'الولايات المتحدة',
      'de': 'Vereinigte Staaten',
      'en': 'United States',
      'es': 'Estados Unidos',
      'fr': 'États-Unis',
      'id': 'Amerika Serikat',
      'ms': 'Amerika Syarikat',
      'pt': 'Estados Unidos',
      'ru': 'США',
      'tr': 'Amerika Birleşik Devletleri',
      'ur': 'ریاستہائے متحدہ',
    },
    'usa': {
      'ar': 'الولايات المتحدة',
      'de': 'USA',
      'en': 'USA',
      'es': 'EE. UU.',
      'fr': 'États-Unis',
      'id': 'AS',
      'ms': 'AS',
      'pt': 'EUA',
      'ru': 'США',
      'tr': 'ABD',
      'ur': 'امریکہ',
    },
    'canada': {
      'ar': 'كندا',
      'de': 'Kanada',
      'en': 'Canada',
      'es': 'Canadá',
      'fr': 'Canada',
      'id': 'Kanada',
      'ms': 'Kanada',
      'pt': 'Canadá',
      'ru': 'Канада',
      'tr': 'Kanada',
      'ur': 'کینیڈا',
    },
    'australia': {
      'ar': 'أستراليا',
      'de': 'Australien',
      'en': 'Australia',
      'es': 'Australia',
      'fr': 'Australie',
      'id': 'Australia',
      'ms': 'Australia',
      'pt': 'Austrália',
      'ru': 'Австралия',
      'tr': 'Avustralya',
      'ur': 'آسٹریلیا',
    },
    'japan': {
      'ar': 'اليابان',
      'de': 'Japan',
      'en': 'Japan',
      'es': 'Japón',
      'fr': 'Japon',
      'id': 'Jepang',
      'ms': 'Jepun',
      'pt': 'Japão',
      'ru': 'Япония',
      'tr': 'Japonya',
      'ur': 'جاپان',
    },
    'morocco': {
      'ar': 'المغرب',
      'de': 'Marokko',
      'en': 'Morocco',
      'es': 'Marruecos',
      'fr': 'Maroc',
      'id': 'Maroko',
      'ms': 'Maghribi',
      'pt': 'Marrocos',
      'ru': 'Марокко',
      'tr': 'Fas',
      'ur': 'مراکش',
    },
    'algeria': {
      'ar': 'الجزائر',
      'de': 'Algerien',
      'en': 'Algeria',
      'es': 'Argelia',
      'fr': 'Algérie',
      'id': 'Aljazair',
      'ms': 'Algeria',
      'pt': 'Argélia',
      'ru': 'Алжир',
      'tr': 'Cezayir',
      'ur': 'الجزائر',
    },
    'tunisia': {
      'ar': 'تونس',
      'de': 'Tunesien',
      'en': 'Tunisia',
      'es': 'Túnez',
      'fr': 'Tunisie',
      'id': 'Tunisia',
      'ms': 'Tunisia',
      'pt': 'Tunísia',
      'ru': 'Тунис',
      'tr': 'Tunus',
      'ur': 'تونس',
    },
    'new zealand': {
      'ar': 'نيوزيلندا',
      'de': 'Neuseeland',
      'en': 'New Zealand',
      'es': 'Nueva Zelanda',
      'fr': 'Nouvelle-Zélande',
      'id': 'Selandia Baru',
      'ms': 'New Zealand',
      'pt': 'Nova Zelândia',
      'ru': 'Новая Зеландия',
      'tr': 'Yeni Zelanda',
      'ur': 'نیوزی لینڈ',
    },
  };

  /// Returns localized city name based on language code.
  static String getLocalizedCity(String city, String langCode) {
    if (city.isEmpty) return city;
    final key = city.trim().toLowerCase();
    final map = _localizedCities[key];
    if (map != null && map.containsKey(langCode)) {
      return map[langCode]!;
    }
    return city;
  }

  /// Returns localized country name based on language code.
  static String getLocalizedCountry(String country, String langCode) {
    if (country.isEmpty) return country;
    final key = country.trim().toLowerCase();
    final map = _localizedCountries[key];
    if (map != null && map.containsKey(langCode)) {
      return map[langCode]!;
    }
    return country;
  }

  /// Returns formatted localized "City, Country" display string.
  static String getLocalizedLocationDisplay(
    String city,
    String country,
    String langCode,
  ) {
    final locCity = getLocalizedCity(city, langCode);
    final locCountry = getLocalizedCountry(country, langCode);
    if (locCity.isEmpty) return locCountry;
    if (locCountry.isEmpty) return locCity;
    return '$locCity, $locCountry';
  }
}
