class SurahLocalizationService {
  static const Map<String, List<String>> _names = {
    'tr': [
      'Fâtiha',
      'Bakara',
      'Âl-i İmrân',
      'Nisâ',
      'Mâide',
      'En\'âm',
      'A\'râf',
      'Enfâl',
      'Tevbe',
      'Yûnus',
      'Hûd',
      'Yûsuf',
      'Ra\'d',
      'İbrâhim',
      'Hicr',
      'Nahl',
      'İsrâ',
      'Kehf',
      'Meryem',
      'Tâhâ',
      'Enbiyâ',
      'Hac',
      'Mü\'minûn',
      'Nûr',
      'Furkân',
      'Şuarâ',
      'Neml',
      'Kasas',
      'Ankebût',
      'Rûm',
      'Lokmân',
      'Secde',
      'Ahzâb',
      'Sebe\'',
      'Fâtır',
      'Yâsîn',
      'Sâffât',
      'Sâd',
      'Zümer',
      'Mü\'min (Gâfir)',
      'Fussilet',
      'Şûrâ',
      'Zuhruf',
      'Duhân',
      'Câsiye',
      'Ahkâf',
      'Muhammed',
      'Fetih',
      'Hucurât',
      'Kâf',
      'Zâriyât',
      'Tûr',
      'Necm',
      'Kamer',
      'Rahmân',
      'Vâkıa',
      'Hadîd',
      'Mücâdele',
      'Haşr',
      'Mümtehine',
      'Saf',
      'Cuma',
      'Münâfikûn',
      'Tegâbün',
      'Talâk',
      'Tahrîm',
      'Mülk',
      'Kalem',
      'Hâkka',
      'Meâric',
      'Nûh',
      'Cin',
      'Müzzemmil',
      'Müddessir',
      'Kıyâmet',
      'İnsan',
      'Mürselât',
      'Nebe\'',
      'Nâziât',
      'Abese',
      'Tekvîr',
      'İnfitâr',
      'Mutaffifîn',
      'İnşikâk',
      'Bürûc',
      'Târık',
      'A\'lâ',
      'Gâşiye',
      'Fecr',
      'Beled',
      'Şems',
      'Leyl',
      'Duhâ',
      'İnşirâh',
      'Tîn',
      'Alak',
      'Kadir',
      'Beyyine',
      'Zilzâl',
      'Âdiyât',
      'Kâria',
      'Tekâsür',
      'Asr',
      'Hümeze',
      'Fîl',
      'Kureyş',
      'Mâûn',
      'Kevser',
      'Kâfirûn',
      'Nasr',
      'Tebbet (Mesed)',
      'İhlâs',
      'Felak',
      'Nâs',
    ],
    'de': [
      'Al-Fatiha',
      'Al-Baqara',
      'Al-Imran',
      'An-Nisa',
      'Al-Ma\'ida',
      'Al-An\'am',
      'Al-A\'raf',
      'Al-Anfal',
      'At-Tauba',
      'Yunus',
      'Hud',
      'Yusuf',
      'Ar-Ra\'d',
      'Ibrahim',
      'Al-Hidschr',
      'An-Nahl',
      'Al-Isra',
      'Al-Kahf',
      'Maryam',
      'Ta-Ha',
      'Al-Anbiya',
      'Al-Hadsch',
      'Al-Mu\'minun',
      'An-Nur',
      'Al-Furqan',
      'Asch-Schu\'ara',
      'An-Naml',
      'Al-Qasas',
      'Al-Ankabut',
      'Ar-Rum',
      'Luqman',
      'As-Sadschda',
      'Al-Ahzab',
      'Saba',
      'Fatir',
      'Ya-Sin',
      'As-Saffat',
      'Sad',
      'Az-Zumar',
      'Ghafir',
      'Fussilat',
      'Asch-Schura',
      'Az-Zukhruf',
      'Ad-Dukhan',
      'Al-Dschathiya',
      'Al-Ahqaf',
      'Muhammad',
      'Al-Fath',
      'Al-Hudschurat',
      'Qaf',
      'Adh-Dhariyat',
      'At-Tur',
      'An-Nadschm',
      'Al-Qamar',
      'Ar-Rahman',
      'Al-Waqi\'a',
      'Al-Hadid',
      'Al-Mudschadila',
      'Al-Haschr',
      'Al-Mumtahana',
      'As-Saff',
      'Al-Dschumu\'a',
      'Al-Munafiqun',
      'At-Taghabun',
      'At-Talaq',
      'At-Tahrim',
      'Al-Mulk',
      'Al-Qalam',
      'Al-Haqqa',
      'Al-Ma\'aridsch',
      'Nuh',
      'Al-Dschinn',
      'Al-Muzzammil',
      'Al-Muddaththir',
      'Al-Qiyama',
      'Al-Insan',
      'Al-Mursalat',
      'An-Naba',
      'An-Nazi\'at',
      'Abasa',
      'At-Takwir',
      'Al-Infitar',
      'Al-Mutaffifin',
      'Al-Inschiqaq',
      'Al-Burudsch',
      'At-Tariq',
      'Al-A\'la',
      'Al-Ghaschiya',
      'Al-Fadschr',
      'Al-Balad',
      'Asch-Schams',
      'Al-Lail',
      'Ad-Duha',
      'Asch-Scharh',
      'At-Tin',
      'Al-Alaq',
      'Al-Qadr',
      'Al-Bayyina',
      'Az-Zalzala',
      'Al-Adiyat',
      'Al-Qari\'a',
      'At-Takathur',
      'Al-Asr',
      'Al-Humaza',
      'Al-Fil',
      'Quraisch',
      'Al-Ma\'un',
      'Al-Kauthar',
      'Al-Kafirun',
      'An-Nasr',
      'Al-Masad',
      'Al-Ikhlas',
      'Al-Falaq',
      'An-Nas',
    ],
    'fr': [
      'Al-Fatiha',
      'Al-Baqara',
      'Al-Imran',
      'An-Nisa',
      'Al-Ma\'ida',
      'Al-An\'am',
      'Al-A\'raf',
      'Al-Anfal',
      'At-Tawba',
      'Younous',
      'Houd',
      'Youssouf',
      'Ar-Ra\'d',
      'Ibrahim',
      'Al-Hijr',
      'An-Nahl',
      'Al-Isra',
      'Al-Kahf',
      'Maryam',
      'Ta-Ha',
      'Al-Anbiya',
      'Al-Hajj',
      'Al-Muminun',
      'An-Nour',
      'Al-Furqane',
      'Ash-Shu\'ara',
      'An-Naml',
      'Al-Qasas',
      'Al-Ankabut',
      'Ar-Rum',
      'Louqman',
      'As-Sajda',
      'Al-Ahzab',
      'Saba',
      'Fatir',
      'Ya-Sin',
      'As-Saffat',
      'Sad',
      'Az-Zumar',
      'Ghafir',
      'Fussilat',
      'Ash-Shura',
      'Az-Zukhruf',
      'Ad-Dukhan',
      'Al-Jathiya',
      'Al-Ahqaf',
      'Mohammed',
      'Al-Fath',
      'Al-Hujurat',
      'Qaf',
      'Adh-Dhariyat',
      'At-Tur',
      'An-Najm',
      'Al-Qamar',
      'Ar-Rahman',
      'Al-Waqi\'a',
      'Al-Hadid',
      'Al-Mujadila',
      'Al-Hashr',
      'Al-Mumtahana',
      'As-Saff',
      'Al-Jumu\'a',
      'Al-Munafiqun',
      'At-Taghabun',
      'At-Talaq',
      'At-Tahrim',
      'Al-Mulk',
      'Al-Qalam',
      'Al-Haqqa',
      'Al-Ma\'arij',
      'Nouh',
      'Al-Jinn',
      'Al-Muzzammil',
      'Al-Muddaththir',
      'Al-Qiyama',
      'Al-Insan',
      'Al-Mursalat',
      'An-Naba',
      'An-Nazi\'at',
      'Abasa',
      'At-Takwir',
      'Al-Infitar',
      'Al-Mutaffifin',
      'Al-Inshiqaq',
      'Al-Buruj',
      'At-Tariq',
      'Al-A\'la',
      'Al-Ghashiya',
      'Al-Fajr',
      'Al-Balad',
      'Ash-Shams',
      'Al-Layl',
      'Ad-Duha',
      'Ash-Sharh',
      'At-Tin',
      'Al-Alaq',
      'Al-Qadr',
      'Al-Bayyina',
      'Az-Zalzala',
      'Al-Adiyat',
      'Al-Qari\'a',
      'At-Takathur',
      'Al-Asr',
      'Al-Humaza',
      'Al-Fil',
      'Quraysh',
      'Al-Ma\'un',
      'Al-Kawthar',
      'Al-Kafirun',
      'An-Nasr',
      'Al-Masad',
      'Al-Ikhlas',
      'Al-Falaq',
      'An-Nas',
    ],
    'es': [
      'Al-Fatiha',
      'Al-Baqara',
      'Al-Imran',
      'An-Nisa',
      'Al-Ma\'ida',
      'Al-An\'am',
      'Al-A\'raf',
      'Al-Anfal',
      'At-Tawba',
      'Yunus',
      'Hud',
      'Yusuf',
      'Ar-Ra\'d',
      'Ibrahim',
      'Al-Hijr',
      'An-Nahl',
      'Al-Isra',
      'Al-Kahf',
      'Maryam',
      'Ta-Ha',
      'Al-Anbiya',
      'Al-Hajj',
      'Al-Mu\'minun',
      'An-Nur',
      'Al-Furqan',
      'Ash-Shu\'ara',
      'An-Naml',
      'Al-Qasas',
      'Al-Ankabut',
      'Ar-Rum',
      'Luqman',
      'As-Sajda',
      'Al-Ahzab',
      'Saba',
      'Fatir',
      'Ya-Sin',
      'As-Saffat',
      'Sad',
      'Az-Zumar',
      'Ghafir',
      'Fussilat',
      'Ash-Shura',
      'Az-Zukhruf',
      'Ad-Dukhan',
      'Al-Jathiya',
      'Al-Ahqaf',
      'Muhammad',
      'Al-Fath',
      'Al-Hujurat',
      'Qaf',
      'Adh-Dhariyat',
      'At-Tur',
      'An-Najm',
      'Al-Qamar',
      'Ar-Rahman',
      'Al-Waqi\'a',
      'Al-Hadid',
      'Al-Mujadila',
      'Al-Hashr',
      'Al-Mumtahana',
      'As-Saff',
      'Al-Jumu\'a',
      'Al-Munafiqun',
      'At-Taghabun',
      'At-Talaq',
      'At-Tahrim',
      'Al-Mulk',
      'Al-Qalam',
      'Al-Haqqa',
      'Al-Ma\'arij',
      'Nuh',
      'Al-Jinn',
      'Al-Muzzammil',
      'Al-Muddaththir',
      'Al-Qiyama',
      'Al-Insan',
      'Al-Mursalat',
      'An-Naba',
      'An-Nazi\'at',
      'Abasa',
      'At-Takwir',
      'Al-Infitar',
      'Al-Mutaffifin',
      'Al-Inshiqaq',
      'Al-Buruj',
      'At-Tariq',
      'Al-A\'la',
      'Al-Ghashiya',
      'Al-Fajr',
      'Al-Balad',
      'Ash-Shams',
      'Al-Layl',
      'Ad-Duha',
      'Ash-Sharh',
      'At-Tin',
      'Al-Alaq',
      'Al-Qadr',
      'Al-Bayyina',
      'Az-Zalzala',
      'Al-Adiyat',
      'Al-Qari\'a',
      'At-Takathur',
      'Al-Asr',
      'Al-Humaza',
      'Al-Fil',
      'Quraysh',
      'Al-Ma\'un',
      'Al-Kawthar',
      'Al-Kafirun',
      'An-Nasr',
      'Al-Masad',
      'Al-Ikhlas',
      'Al-Falaq',
      'An-Nas',
    ],
    'pt': [
      'Al-Fatiha',
      'Al-Baqarah',
      'Aal-Imran',
      'An-Nisa',
      'Al-Ma\'idah',
      'Al-An\'am',
      'Al-A\'raf',
      'Al-Anfal',
      'At-Tawbah',
      'Yunus',
      'Hud',
      'Yusuf',
      'Ar-Ra\'d',
      'Ibrahim',
      'Al-Hijr',
      'An-Nahl',
      'Al-Isra',
      'Al-Kahf',
      'Maryam',
      'Ta-Ha',
      'Al-Anbiya',
      'Al-Hajj',
      'Al-Mu\'minun',
      'An-Nur',
      'Al-Furqan',
      'Ash-Shu\'ara',
      'An-Naml',
      'Al-Qasas',
      'Al-Ankabut',
      'Ar-Rum',
      'Luqman',
      'As-Sajdah',
      'Al-Ahzab',
      'Saba',
      'Fatir',
      'Ya-Sin',
      'As-Saffat',
      'Sad',
      'Az-Zumar',
      'Ghafir',
      'Fussilat',
      'Ash-Shura',
      'Az-Zukhruf',
      'Ad-Dukhan',
      'Al-Jathiyah',
      'Al-Ahqaf',
      'Muhammad',
      'Al-Fath',
      'Al-Hujurat',
      'Qaf',
      'Adh-Dhariyat',
      'At-Tur',
      'An-Najm',
      'Al-Qamar',
      'Ar-Rahman',
      'Al-Waqi\'ah',
      'Al-Hadid',
      'Al-Mujadilah',
      'Al-Hashr',
      'Al-Mumtahanah',
      'As-Saff',
      'Al-Jumu\'ah',
      'Al-Munafiqun',
      'At-Taghabun',
      'At-Talaq',
      'At-Tahrim',
      'Al-Mulk',
      'Al-Qalam',
      'Al-Haqqah',
      'Al-Ma\'arij',
      'Nuh',
      'Al-Jinn',
      'Al-Muzzammil',
      'Al-Muddaththir',
      'Al-Qiyamah',
      'Al-Insan',
      'Al-Mursalat',
      'An-Naba',
      'An-Nazi\'at',
      '\'Abasa',
      'At-Takwir',
      'Al-Infitar',
      'Al-Mutaffifin',
      'Al-Inshiqaq',
      'Al-Buruj',
      'At-Tariq',
      'Al-A\'la',
      'Al-Ghashiyah',
      'Al-Fajr',
      'Al-Balad',
      'Ash-Shams',
      'Al-Layl',
      'Ad-Duha',
      'Ash-Sharh',
      'At-Tin',
      'Al-Alaq',
      'Al-Qadr',
      'Al-Bayyinah',
      'Az-Zalzalah',
      'Al-Adiyat',
      'Al-Qari\'ah',
      'At-Takathur',
      'Al-Asr',
      'Al-Humazah',
      'Al-Fil',
      'Quraysh',
      'Al-Ma\'un',
      'Al-Kawthar',
      'Al-Kafirun',
      'An-Nasr',
      'Al-Masad',
      'Al-Ikhlas',
      'Al-Falaq',
      'An-Nas',
    ],
    'ru': [
      'Аль-Фатиха',
      'Аль-Бакара',
      'Аль Имран',
      'Ан-Ниса',
      'Аль-Маида',
      'Аль-Анам',
      'Аль-Араф',
      'Аль-Анфаль',
      'Ат-Тауба',
      'Юнус',
      'Худ',
      'Юсуф',
      'Ар-Рад',
      'Ибрахим',
      'Аль-Хиджр',
      'Ан-Нахль',
      'Аль-Исра',
      'Аль-Кахф',
      'Марьям',
      'Та Ха',
      'Аль-Анбия',
      'Аль-Хаджж',
      'Аль-Муминун',
      'Ан-Нур',
      'Аль-Фуркан',
      'Аш-Шуара',
      'Ан-Намль',
      'Аль-Касас',
      'Аль-Анкабут',
      'Ар-Рум',
      'Лукман',
      'Ас-Саджда',
      'Аль-Ахзаб',
      'Саба',
      'Фатыр',
      'Йа Син',
      'Ас-Саффат',
      'Сад',
      'Аз-Зумар',
      'Гафир',
      'Фуссилат',
      'Аш-Шура',
      'Аз-Зухруф',
      'Ад-Духан',
      'Аль-Джасия',
      'Аль-Ахкаф',
      'Мухаммад',
      'Аль-Фатх',
      'Аль-Худжурат',
      'Каф',
      'Аз-Зарият',
      'Ат-Тур',
      'Ан-Наджм',
      'Аль-Камар',
      'Ар-Рахман',
      'Аль-Вакиа',
      'Аль-Хадид',
      'Аль-Муджадила',
      'Аль-Хашр',
      'Аль-Мумтахана',
      'Ас-Сафф',
      'Аль-Джума',
      'Аль-Мунафикун',
      'Ат-Тагабун',
      'Ат-Талак',
      'Ат-Тахрим',
      'Аль-Мульк',
      'Аль-Калам',
      'Аль-Хакка',
      'Аль-Мааридж',
      'Нух',
      'Аль-Джинн',
      'Аль-Муззаммиль',
      'Аль-Муддассир',
      'Аль-Кияма',
      'Аль-Инсан',
      'Аль-Мурсалят',
      'Ан-Наба',
      'Ан-Назиат',
      'Абаса',
      'Ат-Таквир',
      'Аль-Инфитар',
      'Аль-Мутаффифин',
      'Аль-Иншикак',
      'Аль-Бурудж',
      'Ат-Тарик',
      'Аль-Аля',
      'Аль-Гашия',
      'Аль-Фаджр',
      'Аль-Балад',
      'Аш-Шамс',
      'Аль-Лейль',
      'Ад-Духа',
      'Аш-Шарх',
      'Ат-Тин',
      'Аль-Алак',
      'Аль-Кадр',
      'Аль-Баййина',
      'Аз-Зальзаля',
      'Аль-Адият',
      'Аль-Кариа',
      'Ат-Такасур',
      'Аль-Аср',
      'Аль-Хумаза',
      'Аль-Филь',
      'Курайш',
      'Аль-Маун',
      'Аль-Каусар',
      'Аль-Кафирун',
      'Ан-Наср',
      'Аль-Масад',
      'Аль-Ихляс',
      'Аль-Фаляк',
      'Ан-Нас',
    ],
    'id': [
      'Al-Fatihah',
      'Al-Baqarah',
      'Ali \'Imran',
      'An-Nisa\'',
      'Al-Ma\'idah',
      'Al-An\'am',
      'Al-A\'raf',
      'Al-Anfal',
      'At-Taubah',
      'Yunus',
      'Hud',
      'Yusuf',
      'Ar-Ra\'d',
      'Ibrahim',
      'Al-Hijr',
      'An-Nahl',
      'Al-Isra\'',
      'Al-Kahf',
      'Maryam',
      'Taha',
      'Al-Anbiya\'',
      'Al-Hajj',
      'Al-Mu\'minun',
      'An-Nur',
      'Al-Furqan',
      'Asy-Syu\'ara\'',
      'An-Naml',
      'Al-Qasas',
      'Al-\'Ankabut',
      'Ar-Rum',
      'Luqman',
      'As-Sajdah',
      'Al-Ahzab',
      'Saba\'',
      'Fatir',
      'Yasin',
      'As-Saffat',
      'Sad',
      'Az-Zumar',
      'Ghafir',
      'Fussilat',
      'Asy-Syura',
      'Az-Zukhruf',
      'Ad-Dukhan',
      'Al-Jasiyah',
      'Al-Ahqaf',
      'Muhammad',
      'Al-Fath',
      'Al-Hujurat',
      'Qaf',
      'Az-Zariyat',
      'At-Tur',
      'An-Najm',
      'Al-Qamar',
      'Ar-Rahman',
      'Al-Waqi\'ah',
      'Al-Hadid',
      'Al-Mujadilah',
      'Al-Hasyr',
      'Al-Mumtahanah',
      'As-Saff',
      'Al-Jumu\'ah',
      'Al-Munafiqun',
      'At-Tagabun',
      'At-Talaq',
      'At-Tahrim',
      'Al-Mulk',
      'Al-Qalam',
      'Al-Haqqah',
      'Al-Ma\'arij',
      'Nuh',
      'Al-Jinn',
      'Al-Muzzammil',
      'Al-Muddassir',
      'Al-Qiyamah',
      'Al-Insan',
      'Al-Mursalat',
      'An-Naba\'',
      'An-Nazi\'at',
      '\'Abasa',
      'At-Takwir',
      'Al-Infitar',
      'Al-Mutaffifin',
      'Al-Insyiqaq',
      'Al-Buruj',
      'At-Tariq',
      'Al-A\'la',
      'Al-Gasyiyah',
      'Al-Fajr',
      'Al-Balad',
      'Asy-Syams',
      'Al-Lail',
      'Ad-Duha',
      'Asy-Syarh',
      'At-Tin',
      'Al-\'Alaq',
      'Al-Qadr',
      'Al-Bayyinah',
      'Az-Zalzalah',
      'Al-\'Adiyat',
      'Al-Qari\'ah',
      'At-Takasur',
      'Al-\'Asr',
      'Al-Humazah',
      'Al-Fil',
      'Quraisy',
      'Al-Ma\'un',
      'Al-Kausar',
      'Al-Kafirun',
      'An-Nasr',
      'Al-Lahab',
      'Al-Ikhlas',
      'Al-Falaq',
      'An-Nas',
    ],
    'ur': [
      'الفاتحہ',
      'البقرہ',
      'آل عمران',
      'النساء',
      'المائدہ',
      'الانعام',
      'الاعراف',
      'الانفال',
      'التوبہ',
      'یونس',
      'ہود',
      'یوسف',
      'الرعد',
      'ابراہیم',
      'الحجر',
      'النحل',
      'الاسراء',
      'الکہف',
      'مریم',
      'طٰہٰ',
      'الانبیاء',
      'الحج',
      'المؤمنون',
      'النور',
      'الفرقان',
      'الشعراء',
      'النمل',
      'القصص',
      'العنکبوت',
      'الروم',
      'لقمان',
      'السجدہ',
      'الاحزاب',
      'سبا',
      'فاطر',
      'یٰسٓ',
      'الصافات',
      'صٓ',
      'الزمر',
      'غافر',
      'فصلت',
      'الشوریٰ',
      'الزخرف',
      'الدخان',
      'الجاثیہ',
      'الاحقاف',
      'محمد',
      'الفتح',
      'الحجرات',
      'قٓ',
      'الذاریات',
      'الطور',
      'النجم',
      'القمر',
      'الرحمن',
      'الواقعہ',
      'الحدید',
      'المجادلہ',
      'الحشر',
      'الممتحنہ',
      'الصف',
      'الجمعہ',
      'المنافقون',
      'التغابن',
      'الطلاق',
      'التحریم',
      'الملک',
      'القلم',
      'الحاقہ',
      'المعارج',
      'نوح',
      'الجن',
      'المزمل',
      'المدثر',
      'القیامہ',
      'الانسان',
      'المرسلات',
      'النبا',
      'النازعات',
      'عبس',
      'التکویر',
      'الانفطار',
      'المطففین',
      'الانشقاق',
      'البروج',
      'الطارق',
      'الاعلیٰ',
      'الغاشیہ',
      'الفجر',
      'البلد',
      'الشمس',
      'اللیل',
      'الضحیٰ',
      'الشرح',
      'التین',
      'العلق',
      'القدر',
      'البینہ',
      'الزلزال',
      'العادیات',
      'القارعہ',
      'التکاثر',
      'العصر',
      'الہمزہ',
      'الفیل',
      'قریش',
      'الماعون',
      'الکوثر',
      'الکافرون',
      'النصر',
      'المسد',
      'الاخلاص',
      'الفلق',
      'الناس',
    ],
    'ms': [
      'Al-Fatihah',
      'Al-Baqarah',
      'Ali \'Imran',
      'An-Nisa\'',
      'Al-Ma\'idah',
      'Al-An\'am',
      'Al-A\'raf',
      'Al-Anfal',
      'At-Taubah',
      'Yunus',
      'Hud',
      'Yusuf',
      'Ar-Ra\'d',
      'Ibrahim',
      'Al-Hijr',
      'An-Nahl',
      'Al-Isra\'',
      'Al-Kahf',
      'Maryam',
      'Taha',
      'Al-Anbiya\'',
      'Al-Hajj',
      'Al-Mu\'minun',
      'An-Nur',
      'Al-Furqan',
      'Asy-Syu\'ara\'',
      'An-Naml',
      'Al-Qasas',
      'Al-\'Ankabut',
      'Ar-Rum',
      'Luqman',
      'As-Sajdah',
      'Al-Ahzab',
      'Saba\'',
      'Fatir',
      'Yasin',
      'As-Saffat',
      'Sad',
      'Az-Zumar',
      'Ghafir',
      'Fussilat',
      'Asy-Syura',
      'Az-Zukhruf',
      'Ad-Dukhan',
      'Al-Jasiyah',
      'Al-Ahqaf',
      'Muhammad',
      'Al-Fath',
      'Al-Hujurat',
      'Qaf',
      'Az-Zariyat',
      'At-Tur',
      'An-Najm',
      'Al-Qamar',
      'Ar-Rahman',
      'Al-Waqi\'ah',
      'Al-Hadid',
      'Al-Mujadilah',
      'Al-Hasyr',
      'Al-Mumtahanah',
      'As-Saff',
      'Al-Jumu\'ah',
      'Al-Munafiqun',
      'At-Tagabun',
      'At-Talaq',
      'At-Tahrim',
      'Al-Mulk',
      'Al-Qalam',
      'Al-Haqqah',
      'Al-Ma\'arij',
      'Nuh',
      'Al-Jinn',
      'Al-Muzzammil',
      'Al-Muddassir',
      'Al-Qiyamah',
      'Al-Insan',
      'Al-Mursalat',
      'An-Naba\'',
      'An-Nazi\'at',
      '\'Abasa',
      'At-Takwir',
      'Al-Infitar',
      'Al-Mutaffifin',
      'Al-Insyiqaq',
      'Al-Buruj',
      'At-Tariq',
      'Al-A\'la',
      'Al-Gasyiyah',
      'Al-Fajr',
      'Al-Balad',
      'Asy-Syams',
      'Al-Lail',
      'Ad-Duha',
      'Asy-Syarh',
      'At-Tin',
      'Al-\'Alaq',
      'Al-Qadr',
      'Al-Bayyinah',
      'Az-Zalzalah',
      'Al-\'Adiyat',
      'Al-Qari\'ah',
      'At-Takasur',
      'Al-\'Asr',
      'Al-Humazah',
      'Al-Fil',
      'Quraisy',
      'Al-Ma\'un',
      'Al-Kausar',
      'Al-Kafirun',
      'An-Nasr',
      'Al-Masad',
      'Al-Ikhlas',
      'Al-Falaq',
      'An-Nas',
    ],
  };

  static const Map<String, List<String>> _meanings = {
    'tr': [
      'Açılış',
      'İnek',
      'İmran Ailesi',
      'Kadınlar',
      'Sofra',
      'Davarlar',
      'Yüksek Yerler',
      'Savaş Ganimetleri',
      'Tevbe',
      'Yunus',
      'Hud',
      'Yusuf',
      'Gök Gürültüsü',
      'İbrahim',
      'Hicr Bölgesi',
      'Arı',
      'Gece Yolculuğu',
      'Mağara',
      'Meryem',
      'Ta-Ha',
      'Peygamberler',
      'Hac',
      'Müminler',
      'Nur',
      'Ölçü',
      'Şairler',
      'Karınca',
      'Kıssalar',
      'Örümcek',
      'Romalılar',
      'Lokman',
      'Secde',
      'Birleşik Kuvvetler',
      'Sebe',
      'Yaratan',
      'Yasin',
      'Saf Tutanlar',
      'Sad Harfi',
      'Topluluklar',
      'Bağışlayan',
      'Ayrıntılı Açıklama',
      'Şûra',
      'Altın Süsler',
      'Duman',
      'Diz Çökme',
      'Kum Tepeleri',
      'Muhammed',
      'Fetih',
      'Odalar',
      'Kaf Harfi',
      'Savuran Rüzgârlar',
      'Tur Dağı',
      'Yıldız',
      'Ay',
      'Rahman',
      'Kaçınılmaz Olan',
      'Demir',
      'Mücadele Eden Kadın',
      'Haşr',
      'Sorgulanacak Kadın',
      'Saflar',
      'Cuma',
      'Münafıklar',
      'Aldanış',
      'Boşanma',
      'Yasaklama',
      'Hükümranlık',
      'Kalem',
      'Gerçekleşecek Olan',
      'Yükselme Yolları',
      'Nuh',
      'Cinler',
      'Örtüsüne Bürünmüş Olan',
      'Elbisesine Bürünmüş Olan',
      'Kıyamet',
      'İnsan',
      'Gönderilenler',
      'Haber',
      'Söküp Çıkaranlar',
      'Yüzünü Ekşitti',
      'Dürülme',
      'Yarılma',
      'Ölçüde Hile',
      'Parçalanma',
      'Burçlar',
      'Gece Gelen',
      'En Yüce',
      'Kaplayan Olay',
      'Şafak',
      'Şehir',
      'Güneş',
      'Gece',
      'Kuşluk Vakti',
      'Ferahlık',
      'İncir',
      'Alak',
      'Kadir',
      'Apaçık Delil',
      'Deprem',
      'Koşan Atlar',
      'Korkunç Olay',
      'Çokluk Yarışı',
      'Asır',
      'Çekiştiren',
      'Fil',
      'Kureyş',
      'Küçük Yardımlar',
      'Bolluk',
      'Kâfirler',
      'Allah’ın Yardımı',
      'Hurma Lifi',
      'İhlas',
      'Tan Yeri',
      'İnsanlar',
    ],
    'de': [
      'Die Eröffnung',
      'Die Kuh',
      'Die Familie Imrans',
      'Die Frauen',
      'Der gedeckte Tisch',
      'Das Vieh',
      'Die Höhen',
      'Die Kriegsbeute',
      'Die Reue',
      'Jona',
      'Hud',
      'Josef',
      'Der Donner',
      'Abraham',
      'Das felsige Gebiet',
      'Die Biene',
      'Die Nachtreise',
      'Die Höhle',
      'Maria',
      'Ta-Ha',
      'Die Propheten',
      'Die Pilgerfahrt',
      'Die Gläubigen',
      'Das Licht',
      'Das Unterscheidungsmerkmal',
      'Die Dichter',
      'Die Ameise',
      'Die Geschichten',
      'Die Spinne',
      'Die Römer',
      'Luqman',
      'Die Niederwerfung',
      'Die Verbündeten',
      'Saba',
      'Der Schöpfer',
      'Ya-Sin',
      'Die in Reihen Aufgestellten',
      'Der Buchstabe Sad',
      'Die Gruppen',
      'Der Vergebende',
      'Ausführlich dargelegt',
      'Die Beratung',
      'Der Goldschmuck',
      'Der Rauch',
      'Die Kniende',
      'Die Sanddünen',
      'Muhammad',
      'Der Sieg',
      'Die Gemächer',
      'Der Buchstabe Qaf',
      'Die zerstreuenden Winde',
      'Der Berg',
      'Der Stern',
      'Der Mond',
      'Der Allerbarmer',
      'Das Unvermeidliche',
      'Das Eisen',
      'Die streitende Frau',
      'Die Verbannung',
      'Die zu prüfende Frau',
      'Die Reihen',
      'Der Freitag',
      'Die Heuchler',
      'Die gegenseitige Täuschung',
      'Die Scheidung',
      'Das Verbot',
      'Die Herrschaft',
      'Der Stift',
      'Die Wirklichkeit',
      'Die Aufstiegswege',
      'Noah',
      'Die Dschinn',
      'Der Eingehüllte',
      'Der Bedeckte',
      'Die Auferstehung',
      'Der Mensch',
      'Die Gesandten',
      'Die Nachricht',
      'Die Herausreißenden',
      'Er runzelte die Stirn',
      'Das Zusammenrollen',
      'Das Spalten',
      'Die Betrüger',
      'Das Aufbrechen',
      'Die Sternbilder',
      'Der Nachtstern',
      'Der Allerhöchste',
      'Das Überwältigende',
      'Die Morgendämmerung',
      'Die Stadt',
      'Die Sonne',
      'Die Nacht',
      'Der Vormittag',
      'Die Erleichterung',
      'Die Feige',
      'Der Blutklumpen',
      'Die Bestimmung',
      'Der klare Beweis',
      'Das Erdbeben',
      'Die Rennenden',
      'Das Verhängnis',
      'Das Streben nach Mehr',
      'Der Nachmittag',
      'Der Verleumder',
      'Der Elefant',
      'Quraisch',
      'Die kleinen Hilfen',
      'Die Fülle',
      'Die Ungläubigen',
      'Die göttliche Hilfe',
      'Die Palmfaser',
      'Die Aufrichtigkeit',
      'Das Morgengrauen',
      'Die Menschen',
    ],
    'fr': [
      'L’Ouverture',
      'La Vache',
      'La Famille d’Imran',
      'Les Femmes',
      'La Table servie',
      'Les Bestiaux',
      'Les Hauteurs',
      'Le Butin',
      'Le Repentir',
      'Jonas',
      'Hud',
      'Joseph',
      'Le Tonnerre',
      'Abraham',
      'La Contrée rocheuse',
      'Les Abeilles',
      'Le Voyage nocturne',
      'La Caverne',
      'Marie',
      'Ta-Ha',
      'Les Prophètes',
      'Le Pèlerinage',
      'Les Croyants',
      'La Lumière',
      'Le Discernement',
      'Les Poètes',
      'Les Fourmis',
      'Le Récit',
      'L’Araignée',
      'Les Romains',
      'Luqman',
      'La Prosternation',
      'Les Coalisés',
      'Saba',
      'Le Créateur',
      'Ya-Sin',
      'Les Rangés',
      'La Lettre Sad',
      'Les Groupes',
      'Le Pardonneur',
      'Les Versets détaillés',
      'La Consultation',
      'L’Ornement',
      'La Fumée',
      'L’Agenouillée',
      'Les Dunes',
      'Muhammad',
      'La Victoire',
      'Les Appartements',
      'La Lettre Qaf',
      'Les Vents qui dispersent',
      'Le Mont',
      'L’Étoile',
      'La Lune',
      'Le Tout Miséricordieux',
      'L’Inéluctable',
      'Le Fer',
      'La Plaideuse',
      'L’Exode',
      'L’Éprouvée',
      'Le Rang',
      'Le Vendredi',
      'Les Hypocrites',
      'La Grande Perte',
      'Le Divorce',
      'L’Interdiction',
      'La Royauté',
      'La Plume',
      'L’Inévitable Vérité',
      'Les Voies d’ascension',
      'Noé',
      'Les Djinns',
      'L’Enveloppé',
      'Le Revêtu d’un manteau',
      'La Résurrection',
      'L’Homme',
      'Les Envoyés',
      'La Nouvelle',
      'Ceux qui arrachent',
      'Il s’est renfrogné',
      'L’Obscurcissement',
      'La Rupture',
      'Les Fraudeurs',
      'La Déchirure',
      'Les Constellations',
      'L’Astre nocturne',
      'Le Très-Haut',
      'L’Enveloppante',
      'L’Aube',
      'La Cité',
      'Le Soleil',
      'La Nuit',
      'Le Matin',
      'Le Soulagement',
      'Le Figuier',
      'L’Adhérence',
      'La Destinée',
      'La Preuve évidente',
      'Le Séisme',
      'Les Coursiers',
      'Le Fracas',
      'La Course aux richesses',
      'Le Temps',
      'Le Calomniateur',
      'L’Éléphant',
      'Quraysh',
      'Les Petits Services',
      'L’Abondance',
      'Les Mécréants',
      'Le Secours divin',
      'La Fibre de palmier',
      'La Sincérité',
      'L’Aube naissante',
      'Les Hommes',
    ],
    'es': [
      'La Apertura',
      'La Vaca',
      'La Familia de Imran',
      'Las Mujeres',
      'La Mesa Servida',
      'Los Ganados',
      'Las Alturas',
      'Los Botines de Guerra',
      'El Arrepentimiento',
      'Jonás',
      'Hud',
      'José',
      'El Trueno',
      'Abraham',
      'La Región Rocosa',
      'La Abeja',
      'El Viaje Nocturno',
      'La Caverna',
      'María',
      'Ta-Ha',
      'Los Profetas',
      'La Peregrinación',
      'Los Creyentes',
      'La Luz',
      'El Criterio',
      'Los Poetas',
      'La Hormiga',
      'Los Relatos',
      'La Araña',
      'Los Romanos',
      'Luqman',
      'La Postración',
      'Los Aliados',
      'Saba',
      'El Originador',
      'Ya-Sin',
      'Los Puestos en Filas',
      'La Letra Sad',
      'Los Grupos',
      'El Perdonador',
      'Explicado Detalladamente',
      'La Consulta',
      'Los Adornos de Oro',
      'El Humo',
      'La Arrodillada',
      'Las Dunas',
      'Muhammad',
      'La Victoria',
      'Las Habitaciones',
      'La Letra Qaf',
      'Los Vientos Dispersores',
      'El Monte',
      'La Estrella',
      'La Luna',
      'El Misericordioso',
      'Lo Inevitable',
      'El Hierro',
      'La Mujer que Discute',
      'El Destierro',
      'La Mujer Examinada',
      'Las Filas',
      'El Viernes',
      'Los Hipócritas',
      'El Desengaño Mutuo',
      'El Divorcio',
      'La Prohibición',
      'La Soberanía',
      'La Pluma',
      'La Realidad',
      'Las Vías de Ascenso',
      'Noé',
      'Los Yinn',
      'El Envuelto',
      'El Cubierto',
      'La Resurrección',
      'El Ser Humano',
      'Los Enviados',
      'La Noticia',
      'Los que Arrancan',
      'Frunció el Ceño',
      'El Arrollamiento',
      'La Hendidura',
      'Los Defraudadores',
      'La Ruptura',
      'Las Constelaciones',
      'El Astro Nocturno',
      'El Altísimo',
      'Lo Abrumador',
      'El Alba',
      'La Ciudad',
      'El Sol',
      'La Noche',
      'La Mañana',
      'El Alivio',
      'La Higuera',
      'El Coágulo',
      'El Poder',
      'La Prueba Clara',
      'El Terremoto',
      'Los Corceles',
      'La Calamidad',
      'La Competencia por Más',
      'El Tiempo',
      'El Difamador',
      'El Elefante',
      'Quraysh',
      'Las Pequeñas Bondades',
      'La Abundancia',
      'Los Incrédulos',
      'El Auxilio Divino',
      'La Fibra de Palma',
      'La Sinceridad',
      'El Amanecer',
      'La Humanidad',
    ],
    'pt': [
      'A Abertura',
      'A Vaca',
      'A Família de Imran',
      'As Mulheres',
      'A Mesa Servida',
      'O Gado',
      'As Alturas',
      'Os Despojos de Guerra',
      'O Arrependimento',
      'Jonas',
      'Hud',
      'José',
      'O Trovão',
      'Abraão',
      'A Região Rochosa',
      'A Abelha',
      'A Viagem Noturna',
      'A Caverna',
      'Maria',
      'Ta-Ha',
      'Os Profetas',
      'A Peregrinação',
      'Os Crentes',
      'A Luz',
      'O Critério',
      'Os Poetas',
      'A Formiga',
      'As Histórias',
      'A Aranha',
      'Os Romanos',
      'Luqman',
      'A Prostração',
      'Os Aliados',
      'Sabá',
      'O Originador',
      'Ya-Sin',
      'Os Enfileirados',
      'A Letra Sad',
      'Os Grupos',
      'O Perdoador',
      'Explicado em Detalhe',
      'A Consulta',
      'Os Adornos de Ouro',
      'A Fumaça',
      'A Ajoelhada',
      'As Dunas',
      'Muhammad',
      'A Vitória',
      'Os Aposentos',
      'A Letra Qaf',
      'Os Ventos Dispersores',
      'O Monte',
      'A Estrela',
      'A Lua',
      'O Misericordioso',
      'O Inevitável',
      'O Ferro',
      'A Mulher que Pleiteia',
      'O Exílio',
      'A Mulher Examinada',
      'As Fileiras',
      'A Sexta-feira',
      'Os Hipócritas',
      'A Desilusão Mútua',
      'O Divórcio',
      'A Proibição',
      'A Soberania',
      'A Pena',
      'A Realidade',
      'As Vias de Ascensão',
      'Noé',
      'Os Jinn',
      'O Envolto',
      'O Coberto',
      'A Ressurreição',
      'O Ser Humano',
      'Os Enviados',
      'A Notícia',
      'Os que Arrancam',
      'Ele Franziu a Testa',
      'O Enrolamento',
      'A Ruptura',
      'Os Fraudadores',
      'A Fenda',
      'As Constelações',
      'A Estrela Noturna',
      'O Altíssimo',
      'O Avassalador',
      'A Aurora',
      'A Cidade',
      'O Sol',
      'A Noite',
      'A Manhã',
      'O Alívio',
      'O Figo',
      'O Coágulo',
      'O Poder',
      'A Prova Clara',
      'O Terremoto',
      'Os Corcéis',
      'A Calamidade',
      'A Competição por Mais',
      'O Tempo',
      'O Difamador',
      'O Elefante',
      'Quraysh',
      'As Pequenas Bondades',
      'A Abundância',
      'Os Descrentes',
      'O Auxílio Divino',
      'A Fibra da Palmeira',
      'A Sinceridade',
      'O Amanhecer',
      'A Humanidade',
    ],
    'ru': [
      'Открывающая',
      'Корова',
      'Семейство Имрана',
      'Женщины',
      'Трапеза',
      'Скот',
      'Ограды',
      'Военные трофеи',
      'Покаяние',
      'Юнус',
      'Худ',
      'Юсуф',
      'Гром',
      'Ибрахим',
      'Аль-Хиджр',
      'Пчёлы',
      'Ночной перенос',
      'Пещера',
      'Марьям',
      'Та-Ха',
      'Пророки',
      'Хадж',
      'Верующие',
      'Свет',
      'Различение',
      'Поэты',
      'Муравьи',
      'Рассказ',
      'Паук',
      'Римляне',
      'Лукман',
      'Земной поклон',
      'Союзники',
      'Саба',
      'Творец',
      'Йа-Син',
      'Выстроившиеся в ряды',
      'Буква Сад',
      'Толпы',
      'Прощающий',
      'Разъяснены',
      'Совет',
      'Украшения',
      'Дым',
      'Коленопреклонённая',
      'Пески',
      'Мухаммад',
      'Победа',
      'Комнаты',
      'Буква Каф',
      'Рассеивающие',
      'Гора',
      'Звезда',
      'Луна',
      'Милостивый',
      'Неизбежное',
      'Железо',
      'Препирающаяся',
      'Сбор',
      'Испытуемая',
      'Ряды',
      'Пятница',
      'Лицемеры',
      'Взаимное обделение',
      'Развод',
      'Запрещение',
      'Власть',
      'Письменная трость',
      'Неминуемое',
      'Ступени',
      'Нух',
      'Джинны',
      'Закутавшийся',
      'Завернувшийся',
      'Воскресение',
      'Человек',
      'Посылаемые',
      'Весть',
      'Исторгающие',
      'Нахмурился',
      'Скручивание',
      'Раскалывание',
      'Обвешивающие',
      'Разверзнется',
      'Созвездия',
      'Ночной путник',
      'Всевышний',
      'Покрывающее',
      'Заря',
      'Город',
      'Солнце',
      'Ночь',
      'Утро',
      'Раскрытие',
      'Смоковница',
      'Сгусток',
      'Предопределение',
      'Ясное знамение',
      'Сотрясение',
      'Скачущие',
      'Великое бедствие',
      'Страсть к приумножению',
      'Время',
      'Хулитель',
      'Слон',
      'Курайш',
      'Мелочь',
      'Изобилие',
      'Неверующие',
      'Помощь',
      'Пальмовые волокна',
      'Искренность',
      'Рассвет',
      'Люди',
    ],
    'id': [
      'Pembukaan',
      'Sapi Betina',
      'Keluarga Imran',
      'Wanita',
      'Hidangan',
      'Binatang Ternak',
      'Tempat Tertinggi',
      'Rampasan Perang',
      'Tobat',
      'Yunus',
      'Hud',
      'Yusuf',
      'Guruh',
      'Ibrahim',
      'Daerah Berbatu',
      'Lebah',
      'Perjalanan Malam',
      'Gua',
      'Maryam',
      'Ta-Ha',
      'Para Nabi',
      'Haji',
      'Orang-orang Mukmin',
      'Cahaya',
      'Pembeda',
      'Para Penyair',
      'Semut',
      'Kisah-kisah',
      'Laba-laba',
      'Bangsa Romawi',
      'Luqman',
      'Sujud',
      'Golongan yang Bersekutu',
      'Saba',
      'Pencipta',
      'Ya-Sin',
      'Yang Bersaf-saf',
      'Huruf Sad',
      'Rombongan',
      'Yang Mengampuni',
      'Yang Dijelaskan',
      'Musyawarah',
      'Perhiasan Emas',
      'Asap',
      'Yang Berlutut',
      'Bukit Pasir',
      'Muhammad',
      'Kemenangan',
      'Kamar-kamar',
      'Huruf Qaf',
      'Angin yang Menerbangkan',
      'Gunung',
      'Bintang',
      'Bulan',
      'Yang Maha Pengasih',
      'Hari Kiamat yang Pasti',
      'Besi',
      'Wanita yang Mengajukan Gugatan',
      'Pengusiran',
      'Wanita yang Diuji',
      'Barisan',
      'Hari Jumat',
      'Orang-orang Munafik',
      'Hari Ditampakkan Kesalahan',
      'Perceraian',
      'Pengharaman',
      'Kerajaan',
      'Pena',
      'Hari Kiamat yang Nyata',
      'Tempat Naik',
      'Nuh',
      'Jin',
      'Orang yang Berselimut',
      'Orang yang Berkemul',
      'Kiamat',
      'Manusia',
      'Para Utusan',
      'Berita Besar',
      'Yang Mencabut',
      'Ia Bermuka Masam',
      'Penggulungan',
      'Terbelah',
      'Orang-orang Curang',
      'Terbelahnya Langit',
      'Gugusan Bintang',
      'Yang Datang pada Malam Hari',
      'Yang Maha Tinggi',
      'Hari Pembalasan',
      'Fajar',
      'Negeri',
      'Matahari',
      'Malam',
      'Waktu Duha',
      'Kelapangan',
      'Buah Tin',
      'Segumpal Darah',
      'Kemuliaan',
      'Bukti Nyata',
      'Guncangan',
      'Kuda Perang yang Berlari Kencang',
      'Hari Kiamat',
      'Bermegah-megahan',
      'Masa',
      'Pengumpat',
      'Gajah',
      'Quraisy',
      'Barang-barang Berguna',
      'Nikmat yang Banyak',
      'Orang-orang Kafir',
      'Pertolongan',
      'Sabut',
      'Ikhlas',
      'Waktu Subuh',
      'Manusia',
    ],
    'ur': [
      'آغاز',
      'گائے',
      'آل عمران',
      'عورتیں',
      'دسترخوان',
      'مویشی',
      'بلندیاں',
      'مال غنیمت',
      'توبہ',
      'یونس',
      'ہود',
      'یوسف',
      'گرج',
      'ابراہیم',
      'پتھریلا علاقہ',
      'شہد کی مکھی',
      'رات کا سفر',
      'غار',
      'مریم',
      'طٰہٰ',
      'انبیاء',
      'حج',
      'مومنون',
      'نور',
      'حق و باطل کا فرق',
      'شعراء',
      'چیونٹی',
      'قصص',
      'مکڑی',
      'رومی',
      'لقمان',
      'سجدہ',
      'اتحادی لشکر',
      'سبا',
      'پیدا کرنے والا',
      'یٰسین',
      'صف باندھنے والے',
      'حرف ص',
      'گروہ',
      'بخشنے والا',
      'تفصیل سے بیان کیا گیا',
      'مشاورت',
      'سنہری زینت',
      'دھواں',
      'گھٹنوں کے بل',
      'ریت کے ٹیلے',
      'محمد',
      'فتح',
      'حجرے',
      'حرف ق',
      'بکھیرنے والی ہوائیں',
      'طور',
      'ستارہ',
      'چاند',
      'نہایت مہربان',
      'واقع ہونے والی',
      'لوہا',
      'بحث کرنے والی عورت',
      'جلاوطنی',
      'آزمائی جانے والی عورت',
      'صفیں',
      'جمعہ',
      'منافق',
      'باہمی نقصان',
      'طلاق',
      'ممانعت',
      'بادشاہی',
      'قلم',
      'حقیقت',
      'چڑھنے کے راستے',
      'نوح',
      'جن',
      'چادر اوڑھنے والا',
      'کپڑا لپیٹنے والا',
      'قیامت',
      'انسان',
      'بھیجے جانے والے',
      'خبر',
      'کھینچ نکالنے والے',
      'اس نے تیوری چڑھائی',
      'لپیٹ دینا',
      'پھٹ جانا',
      'ناپ تول میں کمی کرنے والے',
      'شق ہونا',
      'برج',
      'رات کو آنے والا',
      'سب سے بلند',
      'چھا جانے والی',
      'فجر',
      'شہر',
      'سورج',
      'رات',
      'چاشت',
      'کشادگی',
      'انجیر',
      'علق',
      'قدر',
      'واضح دلیل',
      'زلزلہ',
      'دوڑنے والے گھوڑے',
      'کھڑکھڑانے والی آفت',
      'زیادتی کی دوڑ',
      'زمانہ',
      'طعنہ دینے والا',
      'ہاتھی',
      'قریش',
      'چھوٹی نیکیاں',
      'کثرت',
      'کافر',
      'اللہ کی مدد',
      'کھجور کی رسی',
      'اخلاص',
      'صبح کا اجالا',
      'انسان',
    ],
    'ms': [
      'Pembukaan',
      'Lembu Betina',
      'Keluarga Imran',
      'Wanita',
      'Hidangan',
      'Binatang Ternakan',
      'Tempat Tinggi',
      'Harta Rampasan Perang',
      'Taubat',
      'Yunus',
      'Hud',
      'Yusuf',
      'Guruh',
      'Ibrahim',
      'Kawasan Berbatu',
      'Lebah',
      'Perjalanan Malam',
      'Gua',
      'Maryam',
      'Ta-Ha',
      'Para Nabi',
      'Haji',
      'Orang Beriman',
      'Cahaya',
      'Pembeza',
      'Para Penyair',
      'Semut',
      'Kisah-kisah',
      'Labah-labah',
      'Bangsa Rom',
      'Luqman',
      'Sujud',
      'Golongan Bersekutu',
      'Saba',
      'Pencipta',
      'Ya-Sin',
      'Yang Berbaris',
      'Huruf Sad',
      'Kumpulan',
      'Yang Mengampuni',
      'Dijelaskan dengan Terperinci',
      'Musyawarah',
      'Perhiasan Emas',
      'Asap',
      'Yang Berlutut',
      'Bukit Pasir',
      'Muhammad',
      'Kemenangan',
      'Bilik-bilik',
      'Huruf Qaf',
      'Angin yang Menerbangkan',
      'Gunung',
      'Bintang',
      'Bulan',
      'Yang Maha Pengasih',
      'Yang Tidak Dapat Dielakkan',
      'Besi',
      'Wanita yang Mengadu',
      'Pengusiran',
      'Wanita yang Diuji',
      'Barisan',
      'Hari Jumaat',
      'Orang Munafik',
      'Hari Terbongkar Kerugian',
      'Perceraian',
      'Pengharaman',
      'Kerajaan',
      'Pena',
      'Kenyataan',
      'Jalan Naik',
      'Nuh',
      'Jin',
      'Orang yang Berselimut',
      'Orang yang Berselubung',
      'Kiamat',
      'Manusia',
      'Para Utusan',
      'Berita Besar',
      'Yang Mencabut',
      'Dia Bermasam Muka',
      'Penggulungan',
      'Terbelah',
      'Orang yang Curang',
      'Terbelahnya Langit',
      'Gugusan Bintang',
      'Yang Datang pada Malam',
      'Yang Maha Tinggi',
      'Hari yang Meliputi',
      'Fajar',
      'Negeri',
      'Matahari',
      'Malam',
      'Waktu Duha',
      'Kelapangan',
      'Buah Tin',
      'Segumpal Darah',
      'Kemuliaan',
      'Bukti Nyata',
      'Gegaran',
      'Kuda Perang yang Berlari',
      'Hari Kiamat',
      'Bermegah-megah',
      'Masa',
      'Pengumpat',
      'Gajah',
      'Quraisy',
      'Bantuan Kecil',
      'Nikmat yang Banyak',
      'Orang Kafir',
      'Pertolongan Ilahi',
      'Sabut',
      'Keikhlasan',
      'Fajar Menyingsing',
      'Manusia',
    ],
  };

  static String localizedName(
      int surahNumber, String languageCode, String fallback) {
    final values = _names[languageCode];
    if (values == null || surahNumber < 1 || surahNumber > values.length) {
      return fallback;
    }
    return values[surahNumber - 1];
  }

  static String meaning(int surahNumber, String languageCode, String fallback) {
    final values = _meanings[languageCode];
    if (values == null || surahNumber < 1 || surahNumber > values.length) {
      return fallback;
    }
    return values[surahNumber - 1];
  }
}
